server:
  port: 8082
spring:
  application:
    name: "LoanApplicationMS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST:localhost}
    port: ${ADAPTERS_R2DBC_PORT:5433}
    database: ${ADAPTERS_R2DBC_DATABASE:crediya-loan-applications}
    schema: ${ADAPTERS_R2DBC_SCHEMA:public}
    username: ${ADAPTERS_R2DBC_USERNAME:admin}
    password: ${ADAPTERS_R2DBC_PASSWORD:passwordSQL}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8082"
adapter:
  restconsumer:
    timeout: 5000
    url: ${AUTHENTICATION_MS_URL:http://localhost:8080}
  sqs:
    region: ${SQS_ADAPTER_REGION:us-east-2}
    queueUrl: ${NOTIFICATIONS_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/812612912253/cola-notificaciones-solicitudes}
    calculateCapacityQueueUrl: ${CALCULATE_CAPACITY_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/812612912253/cola-calcular-capacidad}
    updateReportDynamoQueueUrl: ${UPDATE_REPORT_DYNAMO_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/812612912253/cola-actualizar-reporte-dynamo}
jwt:
  json-exp-roles: "/roles"
  secret: ${AUTHENTICATION_JWT_SECRET_KEY:MySecretK3y_MySecretK3y_MySecretK3y_MySecretK3y_}
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
logging:
  level:
    org.springdoc: "DEBUG"
entrypoint:
  sqs:
    region: ${SQS_ENTRYPOINT_REGION:us-east-2}
    queueUrl: ${UPDATE_APPLICATIONS_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/812612912253/cola-actualizar-solicitudes}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
