services:
  loans-postgresql:
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - crediya-loan-applications-data:/var/lib/postgresql/data/
    networks:
      - loan-application-net

  loan-application-ms:
    image: loan-application-ms:latest
    ports:
      - "8082:8082"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ADAPTERS_R2DBC_HOST: loans-postgresql
      ADAPTERS_R2DBC_PORT: 5432
      ADAPTERS_R2DBC_DATABASE: ${ADAPTERS_R2DBC_DATABASE}
      ADAPTERS_R2DBC_SCHEMA: ${ADAPTERS_R2DBC_SCHEMA}
      ADAPTERS_R2DBC_USERNAME: ${ADAPTERS_R2DBC_USERNAME}
      ADAPTERS_R2DBC_PASSWORD: ${ADAPTERS_R2DBC_PASSWORD}
      SQS_ADAPTER_REGION: ${SQS_ADAPTER_REGION}
      NOTIFICATIONS_QUEUE_URL: ${NOTIFICATIONS_QUEUE_URL}
      CALCULATE_CAPACITY_QUEUE_URL: ${CALCULATE_CAPACITY_QUEUE_URL}
      UPDATE_REPORT_DYNAMO_QUEUE_URL: ${UPDATE_REPORT_DYNAMO_QUEUE_URL}
      AUTHENTICATION_JWT_SECRET_KEY: ${AUTHENTICATION_JWT_SECRET_KEY}
      SQS_ENTRYPOINT_REGION: ${SQS_ENTRYPOINT_REGION}
      UPDATE_APPLICATIONS_QUEUE_URL: ${UPDATE_APPLICATIONS_QUEUE_URL}
      AUTHENTICATION_MS_URL: ${AUTHENTICATION_MS_URL}
    depends_on:
      - loans-postgresql
    networks:
      - loan-application-net
      - auth-net

networks:
  loan-application-net:
  auth-net:
    external: true

volumes:
  crediya-loan-applications-data: