services:
  loans-postgresql:
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=passwordSQL
      - POSTGRES_USER=admin
      - POSTGRES_DB=crediya-loan-applications
      - DATABASE_HOST=postgresql
    volumes:
      - crediya-loan-applications-data:/var/lib/postgresql/data/
    networks:
      - loan-application-net

  loan-application-ms:
    image: loan-application-ms:latest
    ports:
      - "8082:8082"
    environment:
      AWS_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ADAPTERS_R2DBC_HOST: postgresql
      ADAPTERS_R2DBC_PORT: 5432
      ADAPTERS_R2DBC_DATABASE: crediya-loan-applications
      ADAPTERS_R2DBC_SCHEMA: public
      ADAPTERS_R2DBC_USERNAME: admin
      ADAPTERS_R2DBC_PASSWORD: passwordSQL
      SQS_ADAPTER_REGION: us-east-2
      NOTIFICATIONS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/812612912253/cola-notificaciones-solicitudes
      CALCULATE_CAPACITY_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/812612912253/cola-calcular-capacidad
      UPDATE_REPORT_DYNAMO_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/812612912253/cola-actualizar-reporte-dynamo
      AUTHENTICATION_JWT_SECRET_KEY: MySecretK3y_MySecretK3y_MySecretK3y_MySecretK3y_
      SQS_ENTRYPOINT_REGION: us-east-2
      UPDATE_APPLICATIONS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/812612912253/cola-actualizar-solicitudes
      AUTHENTICATION_MS_URL: http://authentication:8080
    depends_on:
      - loans-postgresql
    networks:
      - loan-application-net
      - auth-net

networks:
  loan-application-net:
  auth-net:
    external: true

volumes:
  crediya-loan-applications-data: