services:
  postgresql:
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=passwordSQL
      - POSTGRES_USER=admin
      - POSTGRES_DB=crediya-loan-applications
      - DATABASE_HOST=postgresql
    volumes:
      - crediya-loan-applications-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8025:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresql

volumes:
  crediya-loan-applications-data:
  pgadmin-data: